name: Feature Request
description: Suggest a new feature or enhancement for Visitas
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Why is this feature needed?
      placeholder: |
        Example: As a user managing visits, I find it difficult to...
        This would help me by...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: |
        Example: I would like to see a new feature that allows...
        The feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Example: I've tried using..., but it doesn't fully address the need because...
        Another approach could be...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request.
      placeholder: |
        You can attach images by dragging and dropping them here.
        Include any relevant examples, links, or mockups that help illustrate your request.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
